### ISSUE TITLE
jumpTo not working 

### ISSUE THREAD

**Issue by DieGlueckswurst** [Cilestal/clickable_list_wheel_view#2]
and one more thing: `jumpTo` is not working for me.

This is how I implemented it:

`class MyListWheel extends StatefulWidget {
  @override
  _MyListWheelState createState() => _MyListWheelState();
}

class _MyListWheelState extends State<MyListWheel> {
  final _scrollController = FixedExtentScrollController();

  final List months = [
    MonthCardWidget(month: Month('January')),
    MonthCardWidget(month: Month('February')),
    MonthCardWidget(month: Month('March')),
    MonthCardWidget(month: Month('April')),
    MonthCardWidget(month: Month('May')),
    MonthCardWidget(month: Month('Juni')),
    MonthCardWidget(month: Month('Juli')),
    MonthCardWidget(month: Month('August')),
    MonthCardWidget(month: Month('September')),
    MonthCardWidget(month: Month('October')),
    MonthCardWidget(month: Month('November')),
    MonthCardWidget(month: Month('December')),
  ];

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      // only scroll after build is finished
      _scrollController.jumpTo(_scrollController.position.maxScrollExtent);
    });
  }

  @override
  Widget build(BuildContext context) {
    final double _itemHeight = Constants.height(context) / 1.8;

    return ClickableListWheelScrollView(
      scrollController: _scrollController,
      itemHeight: _itemHeight,
      itemCount: months.length,
      scrollOnTap: true,
      onItemTapCallback: (index) {
        print("onItemTapCallback index: $index");
      },
      child: ListWheelScrollView.useDelegate(
        controller: _scrollController,
        itemExtent: _itemHeight,
        physics: FixedExtentScrollPhysics(),
        diameterRatio: 3,
        squeeze: 0.95,
        onSelectedItemChanged: (index) {
          print(index);
        },
        childDelegate: ListWheelChildBuilderDelegate(
          builder: (context, index) => months[index],
          childCount: months.length,
        ),
      ),
    );
  }
}
`

Calling `scrollTo` was working just fine with the normal `listWheelView` but for `clickableListWHeel` it is not working anymore.. Am I missing something here?

**Comment by ghost** [comment]
Instead of jumping to the end of your wheel in `initState`, you can initialize your `_scrollController` as follows:

`final _scrollController = FixedExtentScrollController(initialItem: 11);`

**Comment by DieGlueckswurst** [comment]
working perfectly. `initialItem` makes things even easier for me, thanks!
