### ISSUE TITLE
Doesn't work when using `ListWheelChildLoopingListDelegate`

### ISSUE THREAD

**Issue by bdlukaa** [Cilestal/clickable_list_wheel_view#4]
I have the following implementation:

```dart
ListWheelScrollView.useDelegate(
  controller: ...,
  childDelegate: ListWheelChildLoopingListDelegate(
    children: ...,
  ),
  itemExtent: 36.0,
)
```

But when I try to wrap it in the `ClickableListWheelScrollView` widget, only the first round of widgets work, that means the widgets before the first index and after the last index doesn't get tapped.

**Comment by Cilestal** [comment]
Could you provide the complete code?

**Comment by bdlukaa** [comment]
If I wrap the following widget in a `ClickableListWhellScrollView`, only the first round of widgets gets clicked: https://github.com/bdlukaa/fluent_ui/blob/master/lib/src/controls/form/pickers/date_picker.dart#L390

**Comment by hajimetakase** [comment]
when I change  perspective very low like `perspective: 0.0002` it seems working.

**Comment by hajimetakase** [comment]
or uncomment `physics: FixedExtentScrollPhysics()` also works

**Comment by hajimetakase** [comment]
changing  _getClickedIndex like below works
```
_getClickedIndex() {
    final currentIndex = widget.scrollController.offset ~/ widget.itemHeight;
    final clickOffset = _getClickedOffset();
    final indexOffset = (clickOffset / widget.itemHeight).round();
    final newIndex = currentIndex + indexOffset;

    // if (newIndex < 0 || newIndex >= widget.itemCount) { //uncomment
    //   return -1;
    // }

    return newIndex % widget.itemCount; // new 
  }
```

I guess you need to do something like trueIndexOf()
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/list_wheel_scroll_view.dart#L55

**Comment by bdlukaa** [comment]
> or uncomment `physics: FixedExtentScrollPhysics()` also works

it's not commented

**Comment by Cilestal** [comment]
https://github.com/mbartnik/clickable_list_wheel_view/commit/ac4cca926bd6bbacf4ef537caf7cab3d4d635a02
