### ISSUE TITLE
Wrong item selected after partial scroll with FixedExtentScrollPhysics

### ISSUE THREAD

**Issue by pzet123** [Cilestal/clickable_list_wheel_view#6]
Whenever partially scrolling through the ClickableListWheelScrollView which contains a ListWheelScrollView with FixedExtentScrollPhysics the index of onItemTapCallback is set to the wrong value. When I say partially scrolling I mean scrolling up slightly but then letting go before you move to the item above which causes the list to snap back to the original item. After clicking on the original item, the onItemTapCallback will be called with the index of the item above even though the list is still on the original item. Here is an example of what I mean
![partialscroll](https://user-images.githubusercontent.com/52672507/165489321-ccdb3f86-3b7e-425a-995d-5328d5674b15.gif)

In the gif above you can see I only scroll up partially, not enough to move to the item above, yet when clicking the item in the center, the list moves to the item above as if it was clicked.

The code for this is just the example code from the package page:
```
import 'package:clickable_list_wheel_view/clickable_list_wheel_widget.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Material(
        child: MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  final _scrollController = FixedExtentScrollController();

  static const double _itemHeight = 60;
  static const int _itemCount = 100;

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: ClickableListWheelScrollView(
          scrollController: _scrollController,
          itemHeight: _itemHeight,
          itemCount: _itemCount,
          onItemTapCallback: (index) {
            print("onItemTapCallback index: $index");
          },
          child: ListWheelScrollView.useDelegate(
            controller: _scrollController,
            itemExtent: _itemHeight,
            physics: FixedExtentScrollPhysics(),
            overAndUnderCenterOpacity: 0.5,
            perspective: 0.002,
            onSelectedItemChanged: (index) {
              print("onSelectedItemChanged index: $index");
            },
            childDelegate: ListWheelChildBuilderDelegate(
              builder: (context, index) => _child(index),
              childCount: _itemCount,
            ),
          ),
        ),
      ),
    );
  }

  Widget _child(int index) {
    return SizedBox(
      height: _itemHeight,
      child: ListTile(
        leading: Icon(IconData(int.parse("0xe${index + 200}"), fontFamily: 'MaterialIcons'), size: 50),
        title: Text('Heart Shaker'),
        subtitle: Text('Description here'),
      ),
    );
  }
}
```

**Comment by Cilestal** [comment]
Sorry, I'm not able to maintain the repository at the moment. It would be great if you can fix this problem in new fork.

**Comment by pzet123** [comment]
> Sorry, I'm not able to maintain the repository at the moment. It would be great if you can fix this problem in new fork.

Done

**Comment by Cilestal** [comment]
@pzet123  Thx. I've added changes to release 0.1.0.
