### ISSUE TITLE
Scrolling not working well

### ISSUE THREAD

**Issue by yenyichau** [Cilestal/clickable_list_wheel_view#8]
<img width="301" alt="Screenshot 2022-05-16 at 5 27 09 PM" src="https://user-images.githubusercontent.com/59037547/168562520-5cd9d8b8-abac-46f3-8ed3-862f8d6c0866.png">

When I scroll to between 2 items and it will stop at middle.

**Comment by pzet123** [comment]
set physics to FixedExtentScrollPhysics if you want the widget to snap to items. Your screenshot demonstrates the default list scroll physics.

**Comment by yenyichau** [comment]
> set physics to FixedExtentScrollPhysics if you want the widget to snap to items. Your screenshot demonstrates the default list scroll physics.

Okay thanks I will try it later ❤️
